- name: synflood
  enabled: true
  period: 10s
  polycube.api-url: "http://localhost:9000/polycube/v1/synflood/sf/stats/"

- name: synflood2
  enabled: true
  period: 5s
  polycube.api-url: "http://localhost:9000/polycube/v1/synflood/sf/stats/"
